### PR TITLE
Ability to do any kind of class as value

### PR DESCRIPTION
**Pull request by charlieamer**
I changed code a bit not that much. However I have problems with travis-ci so I didn't have any other option but to add `dist` folder. Please remove it so that it is consistent. If you want to look at important changes, just look at the first commit.

Problem was that this component outputs sometimes array of values and sometimes a single value. The component should be able to accept the value as well (this wasnt working if type of value was, for example number).

### CODE REVIEW

**Comment by hmvs** [comment]
Hello @basvandenberg. Could you please accept this PR or PR#123 ?

**Comment by basvandenberg** [comment]
Sorry, this component gets a bit more attention then I expected. Things slip my attention because a don't have much time to spend on this project.

Correct me if I'm wrong, this seems to be related to #89 and #87.

In #87 I explain why I'd rather not use objects as values (instead of strings). I think the same applies for this PR. Number support might be fine, but I haven't had time to look into #123 yet.

Allowing a generic as options sounds interesting, and as far as I see this seems to be what's in the first commit of this PR. But then there should be some way to ensure this object has a instance variables `value` and `label` of type string, using an Interface for example. I do wan't to consider this, but not for the 1.0 release. My goal is to stabilize the current component, not adding big changes at this point, and getting some testing in place before applying major changes.

**Comment by hmvs** [comment]
I see. Thanks for your efforts. I agree that stabilizing is more important than a new features. But if you can take a look into #123 it's fairly simple, two lines of code.

**Comment by basvandenberg** [comment]
Any object that implements the IOption interface can now be used as option. The values are still strings, which will not change.

**Pull request closed without merging**
